from datetime import datetime
import os


def generate_text_file_name(file_id, current_time):
    """Returns file name, generated by given parameters and in a specific pattern"""
    return str(file_id) + "__" + str(current_time) + ".txt"


def get_fixed_title_text(temp_info, title_text):
    """Adding the fixed title text to the string and returning it"""
    print(title_text)
    text =str(title_text).replace("  ", " ").replace("*", "@").replace("$","@").replace("\r","").replace("\n","$").replace(" $","$")
    #text =str(title_text).replace("\n","$").replace("\r","")
    #text= str("")
    # for line in title_text.split("\n"):
    #text = '\t'.join([line.strip()+("$") for line in title_text])
        
        # print(line)
        # text+= line +"$"
        # print(text)
    #print(text)
    #text= text[:-1]
    print(text)
    return temp_info + "*" + text


def save_image(
    file_type, file_id, current_time, page_number, serial_number, picture, app
):
    """Gets the picuture and the needed parameters and saves it, returns the requird data"""
    file_name = generate_picture_file_name(
        file_type, file_id, current_time, page_number, serial_number
    )
    picture.save(os.path.join(app.config["UPLOAD_FOLDER"], file_name))
    return "*" + str(app.config["UPLOAD_FOLDER"] + file_name)


def get_file_type(file_name):
    """Gets file name and returns it`s type"""
    return file_name.split(".", 1)[1]


def generate_picture_file_name(
    file_type, file_id, current_time, page_number, serial_number
):
    """Returns file name, generated by given parameters and in a specific pattern"""
    return (
        page_number
        + "_"
        + str(serial_number)
        + "__"
        + file_id
        + "__"
        + current_time
        + "."
        + file_type
    )


def set_html_template(
    pic_one, pic_two, pic_three, text, page_num, page_amount, file_type
):
    """Returns html string, generated by given templates and parameters"""
    html_template_name = "pdfPictures/templates/" + file_type + ".html"
    with open(html_template_name, "r", encoding="utf-8") as html_file:
        html_template = html_file.read()

    return (
        html_template.replace("pic_one", pic_one)
        .replace("pic_two", pic_two)
        .replace("pic_three", pic_three)
        .replace("text_from_form", text)
        .replace("page_number", "עמוד " + str(page_num) + " מתוך " + str(page_amount))
        .replace("$","\n")
    )


def generate_page_image_file_name(serial_number, file_id, current_time, file_type):
    """Returns image file name, generated by given parameters and in a specific pattern"""
    return serial_number + "__" + file_id + "__" + current_time + "." + file_type


def generate_pdf_file_name(file_id, current_time):
    """Returns pdf file name, generated by given parameters and in a specific pattern"""
    return file_id + "__" + current_time + ".pdf"


def get_current_time():
    """Returns the current time in a specific pattern"""
    return datetime.now().strftime("%d_%m_%Y_%H_%M_%S")