from datetime import datetime
import os
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from fpdf import FPDF
import appFLinux


def generate_text_file_name(file_id, current_time):
    """Returns file name, generated by given parameters and in a specific pattern"""
    return str(file_id) + "__" + str(current_time) + ".txt"


def get_fixed_title_text(temp_info, title_text):
    """Adding the fixed title text to the string and returning it"""
    return temp_info + "*" + str(title_text).replace("  ", " ").replace("*", "@")


def save_image(
    file_type, file_id, current_time, page_number, serial_number, picture, app
):
    """Gets the picuture and the needed parameters and saves it, returns the requird data"""
    file_name = generate_picture_file_name(
        file_type, file_id, current_time, page_number, serial_number
    )
    picture.save(os.path.join(app.config["UPLOAD_FOLDER"], file_name))
    return "*" + str(app.config["UPLOAD_FOLDER"] + file_name)


def get_file_type(file_name):
    """Gets file name and returns it`s type"""
    return file_name.split(".", 1)[1]


def generate_picture_file_name(
    file_type, file_id, current_time, page_number, serial_number
):
    """Returns file name, generated by given parameters and in a specific pattern"""
    return (
        page_number
        + "_"
        + str(serial_number)
        + "__"
        + file_id
        + "__"
        + current_time
        + "."
        + file_type
    )


def set_html_template(
    pic_one, pic_two, pic_three, text, page_num, page_amount, file_type
):
    """Returns html string, generated by given templates and parameters"""
    html_template_name = "pdfPictures/templates/" + file_type + ".html"
    with open(html_template_name, "r", encoding="utf-8") as html_file:
        html_template = html_file.read()

    return (
        html_template.replace("pic_one", pic_one)
        .replace("pic_two", pic_two)
        .replace("pic_three", pic_three)
        .replace("text_from_form", text)
        .replace("page_number", "עמוד " + str(page_num) + " מתוך " + str(page_amount))
    )


def generate_page_image_file_name(serial_number, file_id, current_time, file_type):
    """Returns image file name, generated by given parameters and in a specific pattern"""
    return serial_number + "__" + file_id + "__" + current_time + "." + file_type


def generate_pdf_file_name(file_id, current_time):
    """Returns pdf file name, generated by given parameters and in a specific pattern"""
    return file_id + "__" + current_time + ".pdf"


def get_current_time():
    """Returns the current time in a specific pattern"""
    return datetime.now().strftime("%d_%m_%Y_%H_%M_%S")


def information_to_pdf(information, file_id, current_time, json_data, app):
    """Gets the current project information and creates the pdf, returns pdf file name"""
    options = Options()
    options.headless = True

    options.add_argument("--window-size=1024,1200")
    options.add_argument("--hide-scrollbars")

    driver = webdriver.Chrome(executable_path="/usr/bin/chromedriver", options=options)
    driver.implicitly_wait(0.5)

    final_images = []
    page_amount = information[-1][0]
    for part in information:
        html_template = set_html_template(
            part[4],
            part[5],
            part[6],
            part[3],
            part[0],
            page_amount,
            part[2],
        )
        image_file_name = generate_page_image_file_name(
            part[0], file_id, current_time, json_data["page_image_type"]
        )
        temp_html_file_name = image_file_name[:-3] + "html"
        with open(
            "/home/ubuntu/nimrod/pdfPictures/templates/" + temp_html_file_name, "w"
        ) as temp_html_file:
            temp_html_file.write(html_template)
            
        print("aa")
        
        with app.app_context():
            appFLinux.load_temp_html_file(html_file=temp_html_file_name)
        url = "http://192.168.0.106:5200/TempHtmlFile/" + temp_html_file_name
        driver.get(url)
        driver.save_screenshot(image_file_name)
        # hti = Html2Image()
        # hti.screenshot(
        #     html_str=html_template,
        #     save_as=image_file_name,
        #     size=(
        #         json_data["screenshot_size"][0],
        #         json_data["screenshot_size"][1],
        #     ),
        # )
        final_images.append(image_file_name)
    driver.close()
    pdf = FPDF("P", "mm", "A4")

    for image in final_images:
        pdf.add_page()
        pdf.image(
            json_data["header_picture_path"],
            w=json_data["header_picure_size"][0],
            h=json_data["header_picure_size"][1],
        )
        pdf.image(
            image,
            w=json_data["pdf_body_size"][0],
            h=json_data["pdf_body_size"][1],
            type=json_data["page_image_type"],
        )
    pdf_file_name = generate_pdf_file_name(file_id, current_time)
    pdf.output(pdf_file_name, "F")

    with open(
        generate_text_file_name(file_id, current_time),
        "a",
        encoding="utf-8",
    ) as text_file:
        text_file.write("Finished*" + "\n")

    return pdf_file_name
