from datetime import datetime

def generate_text_file_name(file_id, current_time):
    """Returns file name, generated by given parameters and in a specific pattern"""
    return str(file_id) + "__" + str(current_time) + ".txt"


def get_fixed_title_text(temp_info, title_text):
    """Adding the fixed title text to the string and returning it"""
    return temp_info + "*" + str(title_text).replace("  ", " ").replace("*", "@")


def get_file_type(file_name):
    """Gets file name and returns it`s type"""
    return file_name.split(".", 1)[1]


def generate_picture_file_name(
    file_type, file_id, current_time, page_number, serial_number
):
    """Returns file name, generated by given parameters and in a specific pattern"""
    return (
        page_number
        + "_"
        + str(serial_number)
        + "__"
        + file_id
        + "__"
        + current_time
        + "."
        + file_type
    )


def set_html_template(
    pic_one, pic_two, pic_three, text, page_num, page_amount, file_type
):
    """Returns html string, generated by given templates and parameters"""
    html_template_name = "pdfPictures/templates/" + file_type + ".html"
    f = open(html_template_name, "r")
    html_template = f.read()
    f.close()

    return (
        html_template.replace("pic_one", pic_one)
        .replace("pic_two", pic_two)
        .replace("pic_three", pic_three)
        .replace("text_from_form", text)
        .replace("page_number", "עמוד " + str(page_num) + " מתוך " + str(page_amount))
    )

def generate_page_image_file_name(serial_number, file_id, current_time, file_type):
    """Returns image file name, generated by given parameters and in a specific pattern"""
    return serial_number + "__" + file_id + "__" + current_time + "." + file_type

def generate_pdf_file_name(file_id, current_time):
    """Returns pdf file name, generated by given parameters and in a specific pattern"""
    return file_id + "__" + current_time + ".pdf"

def get_current_time():
    """Returns the current time in a specific pattern"""
    return datetime.now().strftime("%d_%m_%Y_%H_%M_%S")